Requisitos-de-Software/2023.1-Petz

docs/planejamento/cronograma_realizado.md
mkdocs.yml

| Issue |
|:-----:|
|fixes #|
Criação da página de cronograma realizado e adição do cronograma realizado da etapa 1 da entrega.
@vitormanoel17 
Acredito que o artefato esteja todo ok no sentido de construção, mas preciso da garantia que as datas estejam todas corretas.

create: pagina de cronograma realizado e etapa 1

---

docs/pre-rastreabilidade/richpicture.md

Alterado tipo de arquivo da richpicture v1.
@MastroCoder

fix: Alterado tipo de arquivo da richpicture

---

docs/apresentacoes/apresentacao1.md
docs/atas/reuniao12042023.md
docs/planejamento/cronograma.md
docs/planejamento/cronograma_realizado.md
docs/planejamento/ferramentas.md
docs/planejamento/metodologia.md
docs/pre-rastreabilidade/richpicture.md

Feitos ajustes nas referências bibliográficas para garantir que os artefatos sigam as especificações necessárias.
@PedroFMuniz

fix: ajustes nas referencias

---

docs/atas/reuniao19042023.md

| Issue |
|:-----:|
|fixes #|
Criação da ata da reunião do dia 19/04/2023
- Pedro Muniz 
- Felipe Mastromauro

Atareuniao

---

docs/elicitacao/perfil.md
mkdocs.yml

Foi criada uma página para o perfil de usuário, contendo o perfil inicial e a estrutura para o perfil detalhado final.
@samuel-sato

Create: Perfil inicial para os usuários

---

docs/planejamento/glossario.md
mkdocs.yml

Criação de página de glossário.
@PedroFMuniz

Create: pagina do glossario

---

docs/elicitacao/brainstorming.md
docs/elicitacao/introspeccao.md
docs/elicitacao/tecnicas_planejadas.md
mkdocs.yml

Criado o documento de introspecção e adicionado os requisitos
| Issue #25 |
|:-----:|
|fixes #25 |
Criado o documento de introspecção e adicionado os requisitos. Realizada as atividades de elicitação por introspecção. Criação do documento no docs de "instropeccao".
- Vitor Manoel
- Samuel Sato

change #25 :  documento de introspeccao criado

---

docs/atas/reuniao12042023.md
docs/planejamento/cronograma.md
docs/planejamento/ferramentas.md

Adicionando legendas nas tabelas e chamando no texto.
@PedroFMuniz

Change: Adicionando legendas nas tabelas

---

docs/elicitacao/questionario.md
docs/elicitacao/resultadoElicitacao.md
docs/elicitacao/tecnicas_planejadas.md
mkdocs.yml

| Issue |
|:-----:|
|fixes #|
Criação do documento contendo os requisitos funcionais e não funcionais elicitados
Pedro Muniz
Felipe Corrêa
Vitor Manoel

create: artefato de requisitos e adição de requisitos ao questionário

---

docs/elicitacao/escalaTresNiveis.md
docs/planejamento/ferramentas.md

Correções no artefato de escala de três níveis (adição de outros requisitos) e adição de nova ferramenta.
@PedroFMuniz

Mudancas escala 3 niveis

---

docs/elicitacao/moscow.md
docs/elicitacao/tecnicas_priorizacao.md
mkdocs.yml

Criação da página de técnicas de priorização planejadas e da técnica MoSCoW
@PedroFMuniz

Create: pagina do moscow e tecnicas planejadas

---

docs/elicitacao/custoxbeneficio.md
docs/elicitacao/perfil.md
docs/elicitacao/personas.md
docs/elicitacao/resultadoElicitacao.md
docs/elicitacao/resultadoPriorizacao.md
docs/elicitacao/tecnicas_planejadas.md
mkdocs.yml

Criado documento detalhando os resultados da priorização.
@MastroCoder

Create: artefato para os resultados da priorização

---

docs/elicitacao/custoxbeneficio.md
docs/elicitacao/escalaTresNiveis.md
docs/elicitacao/moscow.md
docs/elicitacao/tecnicas_priorizacao.md

Ajustes de padronização
@MastroCoder

fix: ajustes de padronização

---

docs/apresentacoes/apresentacao2.md
docs/planejamento/cronograma.md
docs/planejamento/cronograma_realizado.md
docs/planejamento/versao_anterior_cronograma.md
mkdocs.yml

Criada página de apresentação da etapa 2, cronograma realizado alterado e alterações no cronograma planejado, bem como a criação de página de versões anteriores dos cronogramas.
@PedroFMuniz

create: página apresentação 2 e cronog.realizado

---

docs/apresentacoes/apresentacao2.md

Adição do vídeo de apresentação

change: Adição do vídeo de apresentação

---

docs/elicitacao/perfil.md
docs/elicitacao/resultadoElicitacao.md
docs/elicitacao/resultadoPriorizacao.md

| Issue |
|:-----:|
|fixes #51 |
Foram realizadas as correções de revisão solicitadas pelo professor.
Fixes #51 
@MastroCoder

fix: correcoes solicitadas

---

docs/elicitacao/brainstorming.md

| Issue |
|:-----:|
|fixes #49 |
Adição do termo de consentimento ao brainstorming.
#49 
@samuel-sato

Brainstorming mudancas

---

docs/atas/reuniao02052023.md
docs/atas/reuniao19042023.md
mkdocs.yml

| Issue |
|:-----:|
|fixes #|
Criação da Ata da reunião do dia 02/05/2023
Vitor Manoel

create: ata dia 02/05/2023

---

docs/modelagem/EspecificacaoSup.md
mkdocs.yml

| Issue |
|:-----:|
|#47 |
Criando artefato de especificação suplementar
@lucascard

Criando artefato especificação suplementar

---

docs/modelagem/EspecificacaoSup.md

adição tabelas

---

docs/modelagem/agil/userStories.md
docs/planejamento/glossario.md
mkdocs.yml

Criado artefato para as histórias de usuário
@samuel-sato

create: Artefato para USs

---

docs/atas/reuniao23052023.md
mkdocs.yml

| Issue |
|:-----:|
|fixes #|
Criação da Ata reunião do dia 23/05/2023
@lucascard

create: criação da ata do dia 23/05/2023

---

docs/apresentacoes/apresentacao3.md
docs/apresentacoes/apresentacao4.md
docs/modelagem/EspecificacaoSup.md
docs/modelagem/agil/userStories.md
docs/modelagem/casos_de_uso.md
docs/planejamento/cronograma_realizado.md

Croação da página de apresentação, cronogramas executados e correções em alguns artefatos
@PedroFMuniz

change: cronograma executado + correções

---

docs/analise/planejamento.md
docs/planejamento/glossario.md

Mudados alguns elementos do planejamento da verificação
@MastroCoder

change: planejamento da analise

---

docs/analise/teste/analiseDocumental.md
docs/analise/teste/lexicos.md
docs/analise/teste/planejamento.md

Verificação dos artefatos de análise documental, planejamento e léxicos.

---

docs/analise/teste/aspectosGerais.md
docs/analise/teste/backlog.md
docs/analise/teste/observacao.md

Criação dos artefatos de verificação para os artefatos de backlog, observação e os aspectos gerais.
@magnluiz

create: verif aspectos gerais, backlog e obs

---

docs/analise/teste/brainstorm.md
docs/analise/teste/escalaTresNiveis.md
docs/analise/teste/nfr.md

Criados artefatos para verificação do brainstorm, escala de três níveis e NFR.
@samuel-sato

create: Artefatos de verificacao

---

docs/analise/teste/especificacaoSuplementar.md
docs/analise/teste/moscow.md
docs/analise/teste/richpicture.md

| Issue |
|:-----:|
|fixes #|
Criação da verificação: Rich Picture, MosCow e Especificação suplementar
@vitormanoel17

Verificacao rich picture

---

docs/analise/teste/especificacaoSuplementar.md
docs/analise/teste/moscow.md
docs/analise/teste/richpicture.md
mkdocs.yml

change: correção da formatação

---

docs/analise/teste/cenarios.md
docs/analise/teste/historiasUsuario.md
docs/analise/teste/personas.md

| Issue |
|:-----:|
|fixes #|
Verificação personas, histórias de usuários e cenários.
@samuel-sato

Verificacao persona/us/cenarios

---

docs/analise/introspeccao.md
docs/analise/storytelling.md

| Issue |
|:-----:|
|fixes #|
@samuel-sato

fix: artefato de verificação introspecção

---

docs/analise/storytelling.md
docs/analise/validacao/prototipagem.md
docs/analise/verif_planejamento.md
docs/elicitacao/resultadoElicitacao.md
docs/modelagem/NFRframework.md
docs/modelagem/agil/backlog.md
docs/modelagem/agil/userStories.md
docs/modelagem/casos_de_uso.md
docs/modelagem/cenarios.md
docs/modelagem/lexico.md
docs/pre-rastreabilidade/richpicture.md
docs/rastreabilidade/matriz.md
docs/rastreabilidade/pre.md
mkdocs.yml

Criados artefatos de pré rastreabilidade e hiperlinks necessários
@MastroCoder

create: artefatos de rastreabilidade

---

docs/analise/especificacaosuplementar.md
docs/apresentacoes/apresentacao7.md
docs/atas/reuniao04072023.md
docs/atas/reuniao13062023.md
docs/atas/reuniao26062023.md
docs/atas/reuniao30062023.md
docs/modelagem/EspecificacaoSup.md
docs/planejamento/cronograma_realizado.md
mkdocs.yml

Tabela e correções da especificação suplementar; término do cronograma executado, adição da apresentação 6 e adição de atas faltantes a partir das definições do WhatsApp.
@magnluiz

Correções Felipe

---

docs/modelagem/lexico.md

Adição de novos léxicos solicitados
@samuel-sato

adição de novos léxicos

---

docs/atas/reuniao01062023.md
docs/atas/reuniao04072023.md
docs/atas/reuniao13062023.md
docs/atas/reuniao26062023.md
docs/atas/reuniao30062023.md

Mudança de ferramenta nas atas
@magnluiz

change: atas com ferramenta errada

---

docs/modelagem/NFRframework.md

Adição dos cartões de especificação dos requisitos não funcionais
@PedroFMuniz

Update nfr cartão de especificação

---

docs/elicitacao/brainstorming.md
docs/modelagem/cenarios.md
docs/modelagem/lexico.md
docs/rastreabilidade/matriz.md

Realizadas correções
@MastroCoder

change: Correções

---

docs/elicitacao/moscow.md
docs/elicitacao/resultadoPriorizacao.md

Atualização do artefato moscow com validação do usuário
@MastroCoder

Atualiza Priorização MosCow

---

docs/apresentacoes/apresentacao5.md
docs/apresentacoes/apresentacao6.md
docs/modelagem/casos_de_uso.md

fix: ajuste apresentacao

---

docs/entregaFinal.md
mkdocs.yml

create: Entrega Final

---

docs/entregaFinal.md

Adição da apresentação final
@PedroFMuniz

Adiciona apresentação final
